// generated by stringer -type=TokenType; DO NOT EDIT

package lex

import "fmt"

const _TokenType_name = "DataTokenArrayOpenArrayCloseDictOpenDictClose"

var _TokenType_index = [...]uint8{0, 9, 18, 28, 36, 45}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
